
def main_register(gpg):
    print "Generating a key, this may take a while"
    input_data = gpg.gen_key_input(key_type="RSA", key_length=1024, name_real=uuid.uuid1(), name_comment="Generated by firehose", name_email="nobody@example.com", passphrase="firehose")
    gpg.gen_key(input_data)
    print "Key generated; now run in chat mode"
